[project]
name = "vision-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.92",
    "pandas>=2.3.3",
    "rfdetr>=1.5.2",
    "roboflow>=1.2.16",
    "split-folders>=0.6.1",
    "supervision>=0.27.0.post1",
    "transformers>=4.57.6",
    "ultralytics>=8.4.21",
]
